openapi: 3.0.0
info:
  title: OpenApi микросервис команды workwolf
  description: |-
    Микросервис дает возможность получить список последних транзакий пользователя с учетом категорий покупок/пополнений
  version: 1.0.0
servers:
  - url: https://workwolf.swagger.io/api/v3
paths:
  /transactions:
    get:
      description: Получить список последних транзакций
      operationId: getTransactions
      responses:
        "200":
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "models.yaml#/components/schemas/Transaction"
