/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi микросервис команды workwolf
 * Микросервис дает возможность получить список последних транзакий пользователя с учетом категорий покупок/пополнений
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
export * from "./models";
