/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi микросервис команды workwolf
 * Микросервис дает возможность получить список последних транзакий пользователя с учетом категорий покупок/пополнений
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Category } from "./category";
/**
 *
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   * @type {number}
   * @memberof Transaction
   * @example 10
   */
  id: number;

  /**
   * Размер транзакции в рублях
   *
   * @type {number}
   * @memberof Transaction
   * @example 4877
   */
  value: number;

  /**
   * Направление транзакции (in – пополнение, out – списание)
   *
   * @type {string}
   * @memberof Transaction
   */
  type: TransactionTypeEnum;

  /**
   * @type {Category}
   * @memberof Transaction
   */
  category?: Category;

  /**
   * Статус транзакции
   *
   * @type {string}
   * @memberof Transaction
   * @example Consumed
   */
  status?: TransactionStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TransactionTypeEnum {
  In = "in",
  Out = "out",
}
/**
 * @export
 * @enum {string}
 */
export enum TransactionStatusEnum {
  AwaitingAuthorisation = "AwaitingAuthorisation",
  Rejected = "Rejected",
  Authorised = "Authorised",
  Consumed = "Consumed",
}
