openapi: 3.0.0
info:
  description: Микросервис дает возможность получить список последних транзакий пользователя
    с учетом категорий покупок/пополнений
  title: OpenApi микросервис команды workwolf
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
paths:
  /transactions/{id}:
    get:
      description: Получить список последних транзакций
      operationId: getTransactions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Transaction'
                type: array
          description: Успешно
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Transaction:
      example:
        id: 10
        type: in
        category:
          name: Рестораны
          id: 1
        value: 4877
        status: Consumed
      properties:
        id:
          example: 10
          format: int64
          type: integer
        value:
          description: Размер транзакции в рублях
          example: 4877
          format: int64
          type: integer
        type:
          description: 'Направление транзакции (in – пополнение, out – списание)'
          enum:
            - in
            - out
          type: string
        category:
          $ref: '#/components/schemas/Category'
        status:
          description: Статус транзакции
          enum:
            - AwaitingAuthorisation
            - Rejected
            - Authorised
            - Consumed
          example: Consumed
          type: string
      required:
        - id
        - type
        - value
      type: object
      xml:
        name: transaction
    Category:
      example:
        name: Рестораны
        id: 1
      properties:
        id:
          example: 1
          format: int64
          type: integer
        name:
          example: Рестораны
          type: string
      type: object
      xml:
        name: category
